import {
	Armchair,
	Baby,
	Backpack,
	Bath,
	BedDouble,
	Book,
	Boxes,
	Briefcase,
	Car,
	CookingPot,
	Cpu,
	Dumbbell,
	Folder,
	Gamepad2,
	Gift,
	Headphones,
	Heart,
	Home,
	Laptop,
	type LucideIcon,
	Music,
	Palette,
	PawPrint,
	Plane,
	Shirt,
	ShoppingBag,
	Smartphone,
	Sofa,
	Sparkles,
	Speaker,
	Tag,
	Tent,
	Utensils,
	Watch,
} from "lucide-react";

export type CategoryIconOption = {
	name: string;
	icon: LucideIcon;
};

export const categoryIcons: CategoryIconOption[] = [
	{ name: "Tag", icon: Tag },
	{ name: "Folder", icon: Folder },
	{ name: "Bag", icon: ShoppingBag },
	{ name: "Home", icon: Home },
	{ name: "Electronics", icon: Smartphone },
	{ name: "Laptop", icon: Laptop },
	{ name: "Hardware", icon: Cpu },
	{ name: "Headphones", icon: Headphones },
	{ name: "Speaker", icon: Speaker },
	{ name: "Furniture", icon: Armchair },
	{ name: "Clothes", icon: Shirt },
	{ name: "Backpack", icon: Backpack },
	{ name: "Travel", icon: Plane },
	{ name: "Car", icon: Car },
	{ name: "Games", icon: Gamepad2 },
	{ name: "Music", icon: Music },
	{ name: "Books", icon: Book },
	{ name: "Food", icon: Utensils },
	{ name: "Sports", icon: Dumbbell },
	{ name: "Art", icon: Palette },
	{ name: "Pets", icon: PawPrint },
	{ name: "Gifts", icon: Gift },
	{ name: "Health", icon: Heart },
	{ name: "Briefcase", icon: Briefcase },
	{ name: "BedDouble", icon: BedDouble },
	{ name: "CookingPot", icon: CookingPot },
	{ name: "Boxes", icon: Boxes },
	{ name: "Sofa", icon: Sofa },
	{ name: "Bath", icon: Bath },
	{ name: "Watch", icon: Watch },
	{ name: "Sparkles", icon: Sparkles },
	{ name: "Baby", icon: Baby },
	{ name: "Tent", icon: Tent },
];
